/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_uci_ics_luci_nomatic_service_sensors_ProcessSensor_Windows */

#ifndef _Included_edu_uci_ics_luci_nomatic_service_sensors_ProcessSensor_Windows
#define _Included_edu_uci_ics_luci_nomatic_service_sensors_ProcessSensor_Windows
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_uci_ics_luci_nomatic_service_sensors_ProcessSensor_Windows
 * Method:    sampleActiveProcess
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_uci_ics_luci_nomatic_service_sensors_ProcessSensor_1Windows_sampleActiveProcess
  (JNIEnv *, jclass);

/*
 * Class:     edu_uci_ics_luci_nomatic_service_sensors_ProcessSensor_Windows
 * Method:    sampleAllProcesses
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_edu_uci_ics_luci_nomatic_service_sensors_ProcessSensor_1Windows_sampleAllProcesses
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
