/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_uci_ics_luci_nomatic_service_sensors_WiFiSensor_Windows */

#ifndef _Included_edu_uci_ics_luci_nomatic_service_sensors_WiFiSensor_Windows
#define _Included_edu_uci_ics_luci_nomatic_service_sensors_WiFiSensor_Windows
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_uci_ics_luci_nomatic_service_sensors_WiFiSensor_Windows
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_uci_ics_luci_nomatic_service_sensors_WiFiSensor_1Windows_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     edu_uci_ics_luci_nomatic_service_sensors_WiFiSensor_Windows
 * Method:    nativeShutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_uci_ics_luci_nomatic_service_sensors_WiFiSensor_1Windows_nativeShutdown
  (JNIEnv *, jclass);

/*
 * Class:     edu_uci_ics_luci_nomatic_service_sensors_WiFiSensor_Windows
 * Method:    getAPSignalStrength
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_edu_uci_ics_luci_nomatic_service_sensors_WiFiSensor_1Windows_getAPSignalStrength
  (JNIEnv *, jclass);

/*
 * Class:     edu_uci_ics_luci_nomatic_service_sensors_WiFiSensor_Windows
 * Method:    getAPSSID
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_uci_ics_luci_nomatic_service_sensors_WiFiSensor_1Windows_getAPSSID
  (JNIEnv *, jclass);

/*
 * Class:     edu_uci_ics_luci_nomatic_service_sensors_WiFiSensor_Windows
 * Method:    _getAPMAC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_uci_ics_luci_nomatic_service_sensors_WiFiSensor_1Windows__1getAPMAC
  (JNIEnv *, jclass);

/*
 * Class:     edu_uci_ics_luci_nomatic_service_sensors_WiFiSensor_Windows
 * Method:    _getAllAPMAC
 * Signature: ()[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_edu_uci_ics_luci_nomatic_service_sensors_WiFiSensor_1Windows__1getAllAPMAC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
