/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BssList */

#ifndef _Included_BssList
#define _Included_BssList
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BssList
 * Method:    getAPsInfo
 * Signature: ()[LBssInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_BssList_getAPsInfo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
